import http from 'node:http';
import https from 'node:https';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';

const root=path.dirname(fileURLToPath(import.meta.url));
const port=Number(process.env.PORT||8787);
const host=process.env.HOST||'0.0.0.0';
const cohort=process.env.YUAN_COHORT||'yuan-global-v1';
const topic=process.env.YUAN_MESH_TOPIC||'yuan/global/v1';
const credentialTtl=Math.max(5*60_000,Number(process.env.YUAN_CREDENTIAL_TTL_MS)||30*60_000);
const maxMessage=Math.max(32*1024,Number(process.env.YUAN_MESH_MAX_MESSAGE)||256*1024);
const maxClients=Math.max(32,Number(process.env.YUAN_MESH_MAX_CLIENTS)||4096);
const providerList=(process.env.YUAN_PROVIDER_URLS||'https://qwen-qwen2-5-omni-7b-demo.hf.space').split(',').map(x=>x.trim().replace(/\/$/,'')).filter(Boolean);
const providers=[...new Set(providerList.filter(x=>{try{return new URL(x).protocol==='https:'}catch{return false}}))];
const seedOrigins=[...new Set((process.env.YUAN_MESH_SEEDS||'').split(',').map(x=>x.trim().replace(/\/$/,'')).filter(x=>{try{return ['https:','http:'].includes(new URL(x).protocol)}catch{return false}}))];
const stateDir=process.env.YUAN_STATE_DIR||root;
const statePath=path.join(stateDir,'.yuan-mesh-ca.json');
const index=fs.readFileSync(path.join(root,'index.html'));
const tokens=new Map(),issueHistory=new Map(),clients=new Set(),federations=new Map();
const health={identityPersistent:false,providers:new Map(),federation:new Map(),lastProbeAt:0};

function canonical(v){if(Array.isArray(v))return '['+v.map(canonical).join(',')+']';if(v&&typeof v==='object')return '{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}';return JSON.stringify(v)}
function b64url(n=24){return crypto.randomBytes(n).toString('base64url')}
function json(res,status,data,head=false){const body=Buffer.from(JSON.stringify(data));res.writeHead(status,{'content-type':'application/json; charset=utf-8','content-length':body.length,'cache-control':'no-store','x-content-type-options':'nosniff'});head?res.end():res.end(body)}
function remoteIp(req){return String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'').split(',')[0].trim()}
function requestOrigin(req,tls){const proto=String(req.headers['x-forwarded-proto']||'').split(',')[0].trim()||(tls?'https':'http');const h=String(req.headers['x-forwarded-host']||req.headers.host||'localhost').split(',')[0].trim();return {proto,host:h}}
function cleanIssued(now=Date.now()){for(const [k,v] of issueHistory){const a=v.filter(t=>now-t<60*60_000);a.length?issueHistory.set(k,a):issueHistory.delete(k)}for(const [k,v] of tokens)if(v.expiresAt<=now)tokens.delete(k)}
function issueAllowed(ip){cleanIssued();const a=issueHistory.get(ip)||[];if(a.length>=12)return false;a.push(Date.now());issueHistory.set(ip,a);return true}
function validIdentity(id,pub){if(!/^[0-9a-f]{64}$/.test(id)||typeof pub!=='string')return false;let raw;try{raw=Buffer.from(pub,'base64')}catch{return false}return raw.length===65&&raw[0]===4&&crypto.createHash('sha256').update(raw).digest('hex')===id}
function readState(){try{const v=JSON.parse(fs.readFileSync(statePath,'utf8'));if(typeof v.privateKeyPem!=='string')return null;const privateKey=crypto.createPrivateKey(v.privateKeyPem),publicKey=crypto.createPublicKey(privateKey);health.identityPersistent=true;return {privateKey,publicKey}}catch{return null}}
function createState(){const env=process.env.YUAN_CA_PRIVATE_KEY_B64;try{if(env){const privateKey=crypto.createPrivateKey(Buffer.from(env,'base64').toString('utf8')),publicKey=crypto.createPublicKey(privateKey);health.identityPersistent=true;return {privateKey,publicKey}}}catch{}
 const pair=crypto.generateKeyPairSync('ec',{namedCurve:'prime256v1'});try{fs.mkdirSync(stateDir,{recursive:true});const privateKeyPem=pair.privateKey.export({type:'pkcs8',format:'pem'}).toString();fs.writeFileSync(statePath,JSON.stringify({privateKeyPem}),{mode:0o600,flag:'wx'});health.identityPersistent=true}catch{health.identityPersistent=false}return pair}
const ca=readState()||createState();
const caPrivate=ca.privateKey,caPublic=ca.publicKey,caDer=caPublic.export({type:'spki',format:'der'}),caPublicKey=caDer.toString('base64'),issuer=crypto.createHash('sha256').update(caDer).digest('hex');
const caJwk=caPublic.export({format:'jwk'}),federationRaw=Buffer.concat([Buffer.from([4]),Buffer.from(caJwk.x,'base64url'),Buffer.from(caJwk.y,'base64url')]),federationPub=federationRaw.toString('base64'),federationId=crypto.createHash('sha256').update(federationRaw).digest('hex');
function signCertificate(id,pub){const issuedAt=Date.now(),expiresAt=issuedAt+credentialTtl,body={id,pub,cohort,issuedAt,expiresAt,serial:b64url(18),issuer};const signature=crypto.sign('sha256',Buffer.from(canonical(body)),{key:caPrivate,dsaEncoding:'ieee-p1363'}).toString('base64');return {...body,signature}}
async function readJson(req){return await new Promise((resolve,reject)=>{let size=0,chunks=[];req.on('data',c=>{size+=c.length;if(size>64*1024){reject(new Error('too-large'));req.destroy();return}chunks.push(c)});req.on('end',()=>{try{resolve(JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}'))}catch(e){reject(e)}});req.on('error',reject)})}
function brokerUrls(req,tls){const o=requestOrigin(req,tls);return [(o.proto==='https'?'wss':'ws')+'://'+o.host+'/yuan-mesh/ws']}
function providerSummary(){return providers.map(url=>({url,ok:health.providers.get(url)?.ok===true,checkedAt:health.providers.get(url)?.at||0}))}
function federationConnected(){return [...federations.values()].filter(x=>x.connected).length}
function federationOnline(){return [...federations.values()].filter(x=>x.connected&&x.compatible).length}
function healthBody(){const providerHealthy=providerSummary().filter(x=>x.ok).length,fedConnected=federationConnected(),fedOnline=federationOnline(),globalMesh=seedOrigins.length>0&&fedOnline>0;return {ok:health.identityPersistent&&providerHealthy>0&&globalMesh&&clients.size<=maxClients,identityPersistent:health.identityPersistent,providers:{configured:providers.length,healthy:providerHealthy,items:providerSummary()},mesh:{localPeers:[...clients].filter(c=>c.authenticated).length,seeds:seedOrigins.length,federationConnected:fedConnected,federationCompatible:fedOnline,global:globalMesh,issuer,cohort},checkedAt:health.lastProbeAt}}
async function probeProvider(url){const started=Date.now();try{const c=new AbortController(),t=setTimeout(()=>c.abort(),8000);let ok=false;try{for(const p of ['/config','/gradio_api/info']){const r=await fetch(url+p,{signal:c.signal,cache:'no-store'});if(r.ok){ok=true;break}}}finally{clearTimeout(t)}health.providers.set(url,{ok,at:Date.now(),latency:Date.now()-started})}catch{health.providers.set(url,{ok:false,at:Date.now(),latency:Date.now()-started})}}
async function probeAll(){await Promise.allSettled(providers.map(probeProvider));health.lastProbeAt=Date.now()}
setInterval(()=>void probeAll(),30_000).unref();void probeAll();

function wsFrame(opcode,payload=Buffer.alloc(0)){const n=payload.length;let head;if(n<126){head=Buffer.alloc(2);head[1]=n}else if(n<65536){head=Buffer.alloc(4);head[1]=126;head.writeUInt16BE(n,2)}else{head=Buffer.alloc(10);head[1]=127;head.writeBigUInt64BE(BigInt(n),2)}head[0]=0x80|opcode;return Buffer.concat([head,payload])}
function wsSend(c,opcode,payload){if(!c.socket.destroyed){const ok=c.socket.write(wsFrame(opcode,Buffer.from(payload)));if(!ok)c.backpressured=true}}
function mqttVar(n){const a=[];do{let d=n%128;n=Math.floor(n/128);if(n)d|=128;a.push(d)}while(n);return Buffer.from(a)}
function mqttPacket(header,payload=Buffer.alloc(0)){return Buffer.concat([Buffer.from([header]),mqttVar(payload.length),payload])}
function mqttText(s){const b=Buffer.from(String(s));const h=Buffer.alloc(2);h.writeUInt16BE(b.length);return Buffer.concat([h,b])}
function readText(buf,at){if(at+2>buf.length)throw new Error('packet');const n=buf.readUInt16BE(at);at+=2;if(at+n>buf.length)throw new Error('packet');return [buf.subarray(at,at+n).toString('utf8'),at+n]}
function parseMqttPackets(buf){const out=[];let at=0;while(at<buf.length){const start=at,header=buf[at++];let mult=1,rem=0,d,count=0;do{if(at>=buf.length)throw new Error('packet');d=buf[at++];rem+=(d&127)*mult;mult*=128;if(++count>4||rem>maxMessage)throw new Error('packet')}while(d&128);if(at+rem>buf.length)throw new Error('packet');out.push({header,type:header>>4,flags:header&15,body:buf.subarray(at,at+rem)});at+=rem;if(at-start>maxMessage)throw new Error('packet')}return out}
function authenticateConnect(c,body){let at=0,name;[name,at]=readText(body,at);if(name!=='MQTT'||at+4>body.length)throw new Error('connect');const version=body[at++],flags=body[at++];at+=2;if(version!==4)throw new Error('connect');let clientId;[clientId,at]=readText(body,at);let username='',password='';if(flags&128)[username,at]=readText(body,at);if(flags&64)[password,at]=readText(body,at);const token=tokens.get(password);if(!token||token.expiresAt<=Date.now()||username!==token.id||!clientId.startsWith('Yuan-'+token.id.slice(0,18)))throw new Error('auth');c.authenticated=true;c.identity=token.id;c.cohort=token.cohort;c.expiresAt=token.expiresAt;c.topic=topic;clearTimeout(c.expiryTimer);c.expiryTimer=setTimeout(()=>closeClient(c),Math.max(1,token.expiresAt-Date.now()));wsSend(c,2,mqttPacket(0x20,Buffer.from([0,0])))}
function broadcastRaw(sender,topicName,payload){const packet=mqttPacket(0x30,Buffer.concat([mqttText(topicName),payload]));for(const c of clients)if(c!==sender&&c.authenticated&&c.subscribed===topicName&&c.cohort===(sender?.cohort||cohort)&&!c.backpressured)wsSend(c,2,packet)}
function federate(payload){for(const f of federations.values())if(f.connected&&f.compatible&&f.ws?.readyState===WebSocket.OPEN)try{f.ws.send(mqttPacket(0x30,Buffer.concat([mqttText(topic),payload])))}catch{}}
function onMqtt(c,p){if(p.type===1){authenticateConnect(c,p.body);return}if(!c.authenticated||c.expiresAt<=Date.now())throw new Error('auth');if(p.type===8){if(p.body.length<5)throw new Error('subscribe');const pid=p.body.subarray(0,2);let t,at;[t,at]=readText(p.body,2);if(t!==c.topic)throw new Error('topic');c.subscribed=t;wsSend(c,2,mqttPacket(0x90,Buffer.concat([pid,Buffer.from([0])])));return}if(p.type===3){let t,at;[t,at]=readText(p.body,0);if(t!==c.topic)throw new Error('topic');const qos=(p.flags>>1)&3;let pid=null;if(qos){if(at+2>p.body.length)throw new Error('packet');pid=p.body.subarray(at,at+2);at+=2}const payload=p.body.subarray(at);if(payload.length>maxMessage)throw new Error('packet');broadcastRaw(c,t,payload);federate(payload);if(qos===1&&pid)wsSend(c,2,mqttPacket(0x40,pid));return}if(p.type===12){wsSend(c,2,mqttPacket(0xD0));return}if(p.type===14){closeClient(c);return}if(p.type===4)return}
function closeClient(c){if(c.closed)return;c.closed=true;clearTimeout(c.expiryTimer);clients.delete(c);try{wsSend(c,8,Buffer.alloc(0))}catch{}try{c.socket.end()}catch{}}
function handleWsFrame(c,opcode,fin,payload){if(opcode===8){closeClient(c);return false}if(opcode===9){wsSend(c,10,payload);return true}if(opcode===0){if(!c.fragmentOpcode)throw new Error('fragment');c.fragments.push(payload);c.fragmentBytes+=payload.length;if(c.fragmentBytes>maxMessage)throw new Error('fragment');if(!fin)return true;opcode=c.fragmentOpcode;payload=Buffer.concat(c.fragments,c.fragmentBytes);c.fragmentOpcode=0;c.fragments=[];c.fragmentBytes=0}else if(!fin){if(opcode!==2)throw new Error('fragment');c.fragmentOpcode=opcode;c.fragments=[payload];c.fragmentBytes=payload.length;return true}if(opcode!==2)return true;for(const p of parseMqttPackets(payload))onMqtt(c,p);return true}
function onWsData(c,chunk){c.buffer=Buffer.concat([c.buffer,chunk]);for(;;){if(c.buffer.length<2)return;const b0=c.buffer[0],b1=c.buffer[1],fin=!!(b0&128),opcode=b0&15,masked=!!(b1&128);if(!masked)throw new Error('mask');let n=b1&127,at=2;if(n===126){if(c.buffer.length<4)return;n=c.buffer.readUInt16BE(2);at=4}else if(n===127){if(c.buffer.length<10)return;const x=c.buffer.readBigUInt64BE(2);if(x>BigInt(maxMessage))throw new Error('frame');n=Number(x);at=10}if(n>maxMessage||c.buffer.length<at+4+n)return;const mask=c.buffer.subarray(at,at+4);at+=4;const payload=Buffer.from(c.buffer.subarray(at,at+n));c.buffer=c.buffer.subarray(at+n);for(let i=0;i<payload.length;i++)payload[i]^=mask[i&3];if(!handleWsFrame(c,opcode,fin,payload))return}}
function attachUpgrade(server){server.on('upgrade',(req,socket)=>{try{if(clients.size>=maxClients){socket.end('HTTP/1.1 503 Service Unavailable\r\nConnection: close\r\n\r\n');return}const u=new URL(req.url,'http://localhost');if(u.pathname!=='/yuan-mesh/ws'||String(req.headers.upgrade||'').toLowerCase()!=='websocket'||!String(req.headers['sec-websocket-protocol']||'').split(',').map(x=>x.trim()).includes('mqtt')){socket.destroy();return}const key=String(req.headers['sec-websocket-key']||'');if(!key){socket.destroy();return}const accept=crypto.createHash('sha1').update(key+'258EAFA5-E914-47DA-95CA-C5AB0DC85B11').digest('base64');socket.write('HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: '+accept+'\r\nSec-WebSocket-Protocol: mqtt\r\n\r\n');const c={socket,buffer:Buffer.alloc(0),authenticated:false,subscribed:'',closed:false,expiryTimer:0,fragmentOpcode:0,fragments:[],fragmentBytes:0,backpressured:false};clients.add(c);socket.on('drain',()=>{c.backpressured=false});socket.on('data',d=>{try{onWsData(c,d)}catch{closeClient(c)}});socket.on('close',()=>closeClient(c));socket.on('error',()=>closeClient(c))}catch{socket.destroy()}})}

function mqttConnectPacket(id,user,password){const variable=Buffer.concat([mqttText('MQTT'),Buffer.from([4,0xc2,0,30])]),payload=Buffer.concat([mqttText(id),mqttText(user),mqttText(password)]);return mqttPacket(0x10,Buffer.concat([variable,payload]))}
function mqttSubscribePacket(name,pid=1){const p=Buffer.alloc(2);p.writeUInt16BE(pid);return mqttPacket(0x82,Buffer.concat([p,mqttText(name),Buffer.from([0])]))}
async function seedCredential(origin){const c=new AbortController(),t=setTimeout(()=>c.abort(),8000);try{const r=await fetch(origin+'/.well-known/yuan-mesh/credential',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:federationId,pub:federationPub}),signal:c.signal});if(!r.ok)throw new Error('seed credential '+r.status);return await r.json()}finally{clearTimeout(t)}}
function onFederationPacket(f,p){if(p.type===2){if(p.body.length<2||p.body[1]!==0)throw new Error('federation auth');f.ws.send(mqttSubscribePacket(topic));return}if(p.type===9){f.connected=true;health.federation.set(f.origin,{ok:f.compatible,connected:true,compatible:f.compatible,at:Date.now()});return}if(p.type===3){let t,at;[t,at]=readText(p.body,0);if(t!==topic)return;const qos=(p.flags>>1)&3;if(qos)at+=2;broadcastRaw({cohort},t,p.body.subarray(at));return}if(p.type===13)return}
async function connectFederation(origin){const state=federations.get(origin)||{origin,ws:null,connected:false,compatible:false,retry:0,timer:0};federations.set(origin,state);if(state.ws&&(state.ws.readyState===WebSocket.OPEN||state.ws.readyState===WebSocket.CONNECTING))return;clearTimeout(state.timer);try{const cred=await seedCredential(origin),broker=(Array.isArray(cred.brokers)?cred.brokers:[]).find(x=>typeof x==='string'&&/^wss?:\/\//.test(x));if(!broker)throw new Error('seed broker');state.compatible=cred.issuer===issuer&&cred.cohort===cohort;const ws=new WebSocket(broker,'mqtt');ws.binaryType='arraybuffer';state.ws=ws;state.connected=false;ws.onopen=()=>{state.retry=0;ws.send(mqttConnectPacket('Yuan-'+federationId.slice(0,18),cred.username,cred.password))};ws.onmessage=e=>{try{const data=Buffer.from(e.data instanceof ArrayBuffer?e.data:new Uint8Array(e.data));for(const p of parseMqttPackets(data))onFederationPacket(state,p)}catch{try{ws.close()}catch{}}};const gone=()=>{state.connected=false;health.federation.set(origin,{ok:false,connected:false,compatible:state.compatible,at:Date.now()});state.ws=null;state.retry++;state.timer=setTimeout(()=>void connectFederation(origin),Math.min(120000,1000*2**Math.min(7,state.retry)));state.timer.unref?.()};ws.onclose=gone;ws.onerror=()=>{try{ws.close()}catch{gone()}}}catch{state.connected=false;health.federation.set(origin,{ok:false,connected:false,compatible:state.compatible,at:Date.now()});state.retry++;state.timer=setTimeout(()=>void connectFederation(origin),Math.min(120000,1000*2**Math.min(7,state.retry)));state.timer.unref?.()}}
for(const seed of seedOrigins)void connectFederation(seed);
setInterval(()=>{for(const seed of seedOrigins)void connectFederation(seed)},60_000).unref();

function makeHandler(tls){return async(req,res)=>{try{const u=new URL(req.url,'http://localhost'),head=req.method==='HEAD';if((req.method==='GET'||head)&&(u.pathname==='/'||u.pathname==='/index.html')){res.writeHead(200,{'content-type':'text/html; charset=utf-8','content-length':index.length,'cache-control':'no-cache','x-content-type-options':'nosniff'});head?res.end():res.end(index);return}if((req.method==='GET'||head)&&u.pathname==='/yuan/health'){const body=healthBody();json(res,body.ok?200:503,body,head);return}if((req.method==='GET'||head)&&u.pathname==='/yuan/providers'){json(res,200,{providers:providerSummary().sort((a,b)=>Number(b.ok)-Number(a.ok)).map(x=>x.url),status:providerSummary()},head);return}if((req.method==='GET'||head)&&u.pathname==='/.well-known/yuan-mesh/status'){const o=requestOrigin(req,tls),body={cohort,issuer,persistentIdentity:health.identityPersistent,broker:(o.proto==='https'?'wss':'ws')+'://'+o.host+'/yuan-mesh/ws',federationConfigured:seedOrigins.length>0,federationConnected:federationConnected(),federationOnline:federationOnline()};json(res,200,body,head);return}if(req.method==='POST'&&(u.pathname==='/.well-known/yuan-mesh/credential'||u.pathname==='/yuan-mesh/credential')){const body=await readJson(req),ip=remoteIp(req);if(!validIdentity(String(body.id||''),String(body.pub||''))){json(res,400,{error:'identity'});return}if(!issueAllowed(ip)){json(res,429,{error:'rate'});return}const certificate=signCertificate(body.id,body.pub),password=b64url(32),expiresAt=certificate.expiresAt;tokens.set(password,{id:body.id,pub:body.pub,cohort,expiresAt,certificate,ip});json(res,200,{brokers:brokerUrls(req,tls),topic,username:body.id,password,expiresAt,cohort,certificate,caPublicKey,issuer,meshScope:seedOrigins.length&&federationOnline()?'global':'deployment',federationOnline:federationOnline()});return}res.writeHead(404,{'content-type':'text/plain; charset=utf-8','cache-control':'no-store'});res.end('Not found')}catch{json(res,500,{error:'server'})}}}

const certPath=process.env.TLS_CERT,keyPath=process.env.TLS_KEY,tls=!!(certPath&&keyPath);
const server=tls?https.createServer({cert:fs.readFileSync(certPath),key:fs.readFileSync(keyPath)},makeHandler(true)):http.createServer(makeHandler(false));
attachUpgrade(server);
server.listen(port,host);
function shutdown(){for(const c of [...clients])closeClient(c);for(const f of federations.values())try{f.ws?.close()}catch{}server.close(()=>process.exit(0));setTimeout(()=>process.exit(1),5000).unref()}
process.once('SIGTERM',shutdown);process.once('SIGINT',shutdown);
